### ISSUE TITLE
Success on my local instance but failing on my work AWS account

### ISSUE THREAD

**Issue by TCJ97** [jdhollis/bastions-on-demand#1]
Hello I have used your bastion on demand server and got it working on my personal AWS account and then created the same on my AWS work account. I'm unable to ssh into the bastion server. I get the following error:

bash-3.2$ ssh ops@$(cat service/.bastion-ip)
ops@54.213.164.29: Permission denied (publickey,keyboard-interactive).

I have uploaded my public ssh key to us-west-2 via the AWS opsworks my settings section. You have any other ideas of what could be different between the two accounts and what I might look into on my Work account to get ssh working?

Thanks this worked really slick on my personal account and I'm hopefully its something my work setup that my account wasn't using. 

Take care Tom

**Comment by jdhollis** [comment]
I’m not terribly familiar with Opsworks, but I would guess that’s where the problem lies.

The `fetch_authorized_keys.sh` script assumes your SSH keys are attached to your IAM user: https://github.com/jdhollis/bastions-on-demand/blob/master/bastion/container/fetch_authorized_keys.sh#L20

Skimming the documentation, it looks like Opswork may be handling its keys independent of IAM. So your best bet would be to see whether Opsworks provides an API for accessing those keys—then, tweak the `fetch_authorized_keys.sh` script accordingly.

Alternatively, make certain your key is attached to your IAM user.

**Comment by TCJ97** [comment]
Thanks for responding so fast. I figured the same as it worked so good on
my private account. I'll look into that. Take care Tom

**Comment by TCJ97** [comment]
you were correct once I added SSH to my IAM account it worked. Thanks
again, Tom

**Comment by jdhollis** [comment]
Glad it worked out. Best of luck!

**Comment by TCJ97** [comment]
Quick Question how can I add more users to this so my whole team can use it
vs just me? We tried adding others IP to sec group below it still doesn't
allow them access.

   1. EC2
   <https://us-west-2.console.aws.amazon.com/ec2/v2/home?region=us-west-2#Home:>
   2. Security Groups
   <https://us-west-2.console.aws.amazon.com/ec2/v2/home?region=us-west-2#SecurityGroups:>
   3. sg-0699a8d976db541c2 - bastions/Tom
   <https://us-west-2.console.aws.amazon.com/ec2/v2/home?region=us-west-2#SecurityGroup:groupId=sg-0699a8d976db541c2>
   4.

   <https://us-west-2.console.aws.amazon.com/ec2/v2/home?region=us-west-2#SecurityGroup:groupId=sg-0699a8d976db541c2>

**Comment by TCJ97** [comment]
Never mind I figured it out. We can just use the service dir and they can
each ramp up their own based on the main setup. Very slick. Do we have to
do anything to be able to access ec2 instances now from the bastion or
should that all just work?

**Comment by jdhollis** [comment]
The idea is that each bastion is specific to a user—people should spin them up and down as needed.

As for accessing other instances via the bastion, you’ll need to make certain the bastion security group has access to those instances, and you’ll need to inject any credentials (such as a shared private key) into the environment on boot. I’ve mostly used these bastions as a way to proxy to other resources rather than to SSH into something, but you may be able to proxy SSH for that as well.

If you're just looking to SSH into EC2 instances, you should also have a look at SSM—it may be a more secure approach.

**Comment by TCJ97** [comment]
Thanks, yes we are looking into that as well but this was easier to
implement to get started. Thanks again for all the help.
